cover_letter:
  career_start_year: 2010
  mandatory_skills:
  - Java
  - Perl
  - Kommandozeile (Console)
  - Künstliche Intelligenz (AI / LLM / KI)
  - Linux
  - Technischer Spezialist IT
  - Backend
  - Back-end
  - Junior
  - Trainee
  - Praktikum
  - Russisch
  - Ukrainisch
  - AI
  - KI
  - System Administrator
  - IT Administrator
  - KfZ-Mechaniker
  - PKW-Fahrer
  - Fuhrerschein Klasse B
  - Fahrerlaubnis Klasse B
  - Sicherheitsmitarbeiter
  - Reisebereitschaft
  - Bereitschaft zu Dienstreisen
  - Remotearbeit
  - Hybridarbeit
  - Homeoffice
  - Vor Orts Arbeit
ko_filters:
  certifications:
    mandatory_if_specified:
    - RHCSA
    - RHCE
    - CCNA
  clearances:
    forbidden_keywords:
    - U.S. citizenship
    - security clearance
    - TESA status
    - Secret clearance
    - Top Secret clearance
  companies_blacklist:
  - Zukunftsmotor
  - Zukunftsmotor GmbH
  datacenter_physical_work:
    forbidden: true
    keywords: []
  education:
    block_degree_only_roles: true
    require_it_degree_strictly: true
  forbidden_titles:
  - Full Stack Developer
  - Fullstack Developer
  - Senior
  - Middle
  - Consultant
  - Projektmanager
  - Middle
  - Helpdesk
  - Help desk
  - Produktspezialist
  languages:
    min_required_english: A2
    min_required_german: B1
  salary:
    min_annual_eur: 36000
  spam_providers:
    allow_internship: true
    blocked_keywords:
    - GFN
    - WBS
    - DAA
    - IU
  user_rejected_reasons:
  - Erfahrung im direkten Kontakt mit Kunden.
  - Annahme und Bearbeitung von Supportanfragen:Telefon.
  - Ein aufenthaltsrechtlicher Titel.
scoring:
  min_score_to_apply: 5.0
